site_name: CS for Backend Developer
site_url: https://CokaNuri.github.io/CSBE/
docs_dir: docs

theme:
  name: material
  language: ko
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 다크 모드로 전환
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 라이트 모드로 전환
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - toc.permalink

nav:
  - Home: index.md
  - 소프트웨어 공학:
    - Chapter 1:
      - 소프트웨어 공학 개요: "software-engineering/Chapter 1/01 소프트웨어 공학 개요.md"
    - Chapter 2:
      - 소프트웨어 품질: "software-engineering/Chapter 2/01 소프트웨어 품질.md"
      - 인공지능 소프트웨어 품질: "software-engineering/Chapter 2/02 인공지능 소프트웨어 품질.md"
      - 소프트웨어 품질 모델 및 표준: "software-engineering/Chapter 2/03 소프트웨어 품질 모델 및 표준.md"
    - Chapter 3:
      - 실현 가능성 분석: "software-engineering/Chapter 3/01 실현 가능성 분석.md"
      - 전통적인 소프트웨어 프로세스: "software-engineering/Chapter 3/02 전통적인 소프트웨어 프로세스.md"
      - 애자일 및 XP 프로세스: "software-engineering/Chapter 3/03 애자일 및 XP 프로세스.md"
      - 소프트웨어 프로세스 개선: "software-engineering/Chapter 3/04 소프트웨어 프로세스 개선.md"
    - Chapter 4:
      - DevOps 개요: "software-engineering/Chapter 4/01 DevOps 개요.md"
      - DevOps 프로세스와 프랙티스: "software-engineering/Chapter 4/02 DevOps 프로세스와 프랙티스.md"
      - DevOps 변형들: "software-engineering/Chapter 4/03 DevOps 변형들.md"
    - Chapter 5:
      - 프로젝트 관리 필요성: "software-engineering/Chapter 5/01 프로젝트 관리 필요성.md"
      - 프로젝트 관리 기법: "software-engineering/Chapter 5/02 프로젝트 관리 기법.md"
      - 프로젝트 조직: "software-engineering/Chapter 5/03 프로젝트 조직.md"
      - 프로젝트 관리 계획서: "software-engineering/Chapter 5/04 프로젝트 관리 계획서.md"
      - 프로젝트 지원 도구: "software-engineering/Chapter 5/05 프로젝트 지원 도구.md"

plugins:
  - search:
      lang: ko

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      permalink: true
